version: '3.9'
# To execute this docker-compose yml file use command:
#   docker-compose -f <file_name> up [--build] [--no-start] [--no-build] [--force-recreate / --no-recreate] [--detach]
# For more info about options: docker-compose up --help


services:
  adbscan:
    image: ${REPO_URL}amr-adbscan:${DOCKER_TAG:-latest}
    container_name: ${CONTAINER_NAME_PREFIX:-amr-}adbscan
    extends:
      file:  ../common/container-launch-env.yml
      service: container-launch-env
    build:
      target: adbscan
    # We enter into bash shell of docker-container
    command:
    - |
       export ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
       source ros_entrypoint.sh
       source /home/eiforamr/workspace/source_prebuilt_components.sh
       cd ${CONTAINER_BASE_PATH}/01_docker_sdk_env/docker_compose/06_bags/
       sudo chown -R eiforamr:root laser_pointcloud_spinning
       sudo chmod -R 777 laser_pointcloud_spinning
       # Run, in a loop, the ros2 bag recorded with a RealSense Camera
       ros2 bag play --loop laser_pointcloud_spinning &
       cd /home/eiforamr/ros2_ws/install/adbscan_ros2/lib/adbscan_ros2
       # Start adbscan application with RealSense camera as point cloud source
       ros2 run adbscan_ros2 adbscan_sub --ros-args --params-file ${CONTAINER_BASE_PATH}/01_docker_sdk_env/artifacts/01_amr/amr_generic/param/adbscan_RS_params.yaml &
       # Run Rviz application to display adbscan /scan and /marker_array topics
       ros2 run rviz2 rviz2 -d ${CONTAINER_BASE_PATH}/01_docker_sdk_env/artifacts/01_amr/amr_generic/config/adbscan_RS_config.rviz
