version: '3.9'
# To execute this docker-compose yml file use command:
##   docker-compose -f <file_name> up [--build] [--no-start] [--no-build] [--force-recreate / --no-recreate] [--detach]
# For more info about options: docker-compose up --help

services:

  full-sdk:
    image: ${REPO_URL}eiforamr-full-flavour-sdk:${DOCKER_TAG:-latest}
    container_name: ${CONTAINER_NAME_PREFIX:-eiforamr-}full-sdk
    extends:
      file:  ../common/container-launch-env.yml
      service: container-launch-env
    build:
      target: full-sdk
    command:
      - |
        export ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
        export TURTLEBOT3_MODEL=waffle
        export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/home/eiforamr/ros2_ws/install/turtlebot3_gazebo/share/turtlebot3_gazebo/models/
        ros2 launch nav2_bringup tb3_simulation_launch.py params_file:=${CONTAINER_BASE_PATH}/01_docker_sdk_env/artifacts/01_amr/amr_generic/param/its_nav2_params.yaml
