# INTEL CONFIDENTIAL

# Copyright 2021 Intel Corporation.

# This software and the related documents are Intel copyrighted materials, and
# your use of them is governed by the express license under which they were
# provided to you ("License"). Unless the License provides otherwise, you may
# not use, modify, copy, publish, distribute, disclose or transmit this
# software or the related documents without Intel's prior written permission.

# This software and the related documents are provided as is, with no express
# or implied warranties, other than those that are expressly stated in the
# License.

version: "3.8"
services:
  fleet-management:
    image: ${REPO_URL}amr-fleet-management:${DOCKER_TAG:-latest}
    container_name: ${CONTAINER_NAME_PREFIX:-amr-}fleet-management
    ipc: host
    network_mode: "host"
    restart: always
    cap_add:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /run/lock
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      - /lib/modules/`uname -r`:/lib/modules/`uname -r`
      - /dev:/dev
      - /var/tmp:/var/tmp
      - /var/persistent-log/mosquitto
      - /lib/firmware:/lib/firmware
      - /lib/firmware/flashless_backup
      - /usr/lib/libXLink.so:/usr/lib/libXLink.so
      - /:/host
      - /var/cache/manageability/:/var/cache/manageability/
      - /opt/xlink_provision:/opt/xlink_provision
      - /tmp:/tmp
      - /etc/amr/certs:/var/certs
      - /etc/tc:/etc/tc
    devices:
      - "/dev/xlnk:/dev/xlnk"
    tty: true
 
