version: '3.9'
# To execute this docker-compose yml file use command:
#   docker-compose -f <file_name> up [--build] [--no-start] [--no-build] [--force-recreate / --no-recreate] [--detach]
# For more info about options: docker-compose up --help


services:
  oneapi:
    image: ${REPO_URL}eiforamr-full-flavour-sdk:${DOCKER_TAG:-latest}
    container_name: ${CONTAINER_NAME_PREFIX:-amr-}oneapi
    env_file:
      - ../05_tutorials/.env
    extends:
      file: ../common/common.yml
      service: common
    build:
      context: ${CONTEXT_DIR:-../..}
      dockerfile: ./dockerfile.amr
      target: oneapi
    restart: "no"
    network_mode: host
    # We enter into bash shell of docker-container
    command:
    - |
       echo "******* Download and copy the matrix_multiply_vtune in tmp and change directory to VTune™ Profiler: *******"
       git clone https://github.com/oneapi-src/oneAPI-samples.git
       cp -rf oneAPI-samples/Tools/VTuneProfiler/matrix_multiply_vtune/ /tmp/matrix_multiply_vtune
       cd /tmp/matrix_multiply_vtune
       echo "******* Build the Matrix Multiplication sample *******"
       . /opt/intel/oneapi/setvars.sh
       cmake .
       make
       echo "******* Run the application with VTune™ Profiler *******"
       /opt/intel/oneapi/vtune/latest/bin64/vtune -collect gpu-hotspots ./matrix.dpcpp
