# INTEL CONFIDENTIAL

# Copyright 2021 Intel Corporation.

# This software and the related documents are Intel copyrighted materials, and
# your use of them is governed by the express license under which they were
# provided to you ("License"). Unless the License provides otherwise, you may
# not use, modify, copy, publish, distribute, disclose or transmit this
# software or the related documents without Intel's prior written permission.

# This software and the related documents are provided as is, with no express
# or implied warranties, other than those that are expressly stated in the
# License.

version: "3.9"
services:
  wwan-5g-modem:
    image: ${REPO_URL}amr-wwan-5g-modem:${DOCKER_TAG:-latest}
    container_name: ${CONTAINER_NAME_PREFIX:-amr-}wwan-5g-modem
    extends:
      file: ../common/common.yml
      service: common
    build:
      target: wwan-5g-modem
    tmpfs:
      - /run
      - /run/lock
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /dev:/dev
      - /var/run/dbus:/var/run/dbus
      - /run/systemd:/run/systemd
      - /run/systemd/system:/run/systemd/system
      - /tmp/:/tmp 
    tty: true
    